### ISSUE TITLE
Great initiative

### ISSUE THREAD

**Issue by thiagoesteves** [s3cur3/example_test#2]
I have been writing these kind of multiple inputs for the same test body using Macros, but this solution seems very cleaner. I would just suggest another name, like Parameterized Tests or similar.

**Comment by s3cur3** [comment]
Thanks for the kind words! I agree it probably needs a name change. 😅 Parameterized tests is accurate, but it's both longer and harder to spell if we make that the primary macro (`parameterized_test`).

**Comment by s3cur3** [comment]
I settled on calling the package `ParameterizedTest`, with the macro for using it being `param_test`. I'm gonna release it as v0.1.0 soon. ☺️
